// AUTO-GENERATED by Bonza AEO — do not edit by hand. Structured data for answer engines
// (Google AI Overviews, ChatGPT, Perplexity, Gemini). Regenerated on each AEO sync.
const GRAPH = [
  {
    "@context": "https://schema.org",
    "@type": "AutoRepair",
    "@id": "https://brookswoodautomotive.co.uk/#business",
    "name": "Brookswood Automotive LTD",
    "url": "https://brookswoodautomotive.co.uk",
    "telephone": "01329 640779",
    "email": "info@brookswoodautomotive.co.uk",
    "image": "https://hppgzamzudygkyyzkgdd.supabase.co/storage/v1/object/public/website-media/logos/1786203141984-ze14e1fqyhd-logo-pos.webp",
    "address": {
      "@type": "PostalAddress",
      "addressCountry": "GB",
      "postalCode": "PO14 1AJ",
      "streetAddress": "4-6 Hackett Way",
      "addressLocality": "Fareham"
    },
    "geo": {
      "@type": "GeoCoordinates",
      "latitude": 50.84068320000001,
      "longitude": -1.1844491
    },
    "areaServed": [
      {
        "@type": "City",
        "name": "Fareham"
      }
    ],
    "openingHoursSpecification": [
      {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": "https://schema.org/Monday",
        "opens": "08:30",
        "closes": "17:30"
      },
      {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": "https://schema.org/Tuesday",
        "opens": "08:30",
        "closes": "17:30"
      },
      {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": "https://schema.org/Wednesday",
        "opens": "08:30",
        "closes": "17:30"
      },
      {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": "https://schema.org/Thursday",
        "opens": "08:30",
        "closes": "17:30"
      },
      {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": "https://schema.org/Friday",
        "opens": "08:30",
        "closes": "17:30"
      },
      {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": "https://schema.org/Saturday",
        "opens": "08:30",
        "closes": "12:30"
      }
    ],
    "sameAs": [
      "https://www.google.com/maps/place/?q=place_id:ChIJ38sU16ON0AYR99K3RnbQedo"
    ]
  },
  {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What areas does Brookswood Automotive LTD cover?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Brookswood Automotive LTD serves Fareham."
        }
      },
      {
        "@type": "Question",
        "name": "Do you cover Fareham?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes — Brookswood Automotive LTD covers Fareham and the surrounding area."
        }
      },
      {
        "@type": "Question",
        "name": "How do I contact Brookswood Automotive LTD?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Call 01329 640779 or email info@brookswoodautomotive.co.uk."
        }
      },
      {
        "@type": "Question",
        "name": "What are Brookswood Automotive LTD's opening hours?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Monday: 08:30–17:30; Tuesday: 08:30–17:30; Wednesday: 08:30–17:30; Thursday: 08:30–17:30; Friday: 08:30–17:30; Saturday: 08:30–12:30; Sunday: Closed"
        }
      }
    ]
  }
] as const

export function StructuredData() {
  return (
    <>
      {GRAPH.map((node, i) => (
        <script
          key={i}
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(node) }}
        />
      ))}
    </>
  )
}
